<?php

namespace AppBundle\Repository;

/**
 * BreweriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class BreweriesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findThreeNearestBreweries()
    {
        $qb = $this->createQueryBuilder('b');
        $qb->select('b');
        $qb->from('AppBundle:Breweries','c');
        $qb->where('b >= 1122');
        $qb->setFirstResult(3);
//        $qb->setParameter(0, '%');
        return $qb->getQuery()->getResult();
    }

//    public function findOpenBrewery($input)
//    {
//        $qb = $this->createQueryBuilder('c');
//        $qb->select('DAYNAME(CURRENT_DATE)');
////        $qb->join('c.make', 'make');
////        $qb->join('c.model', 'model');
//        return $qb->getQuery()->getResult();
////    }


}
