<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Breweries;
use \Doctrine\ORM\NoResultException;

/**
 * BreweriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class BreweriesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     *
     * @return Breweries[]
     */
    public function findNearestBreweries()
    {
        return $this->createQueryBuilder('breweries')
            ->andWhere('breweries.zipcode = :zipcode')
            ->setParameter('zipcode', true)
            ->orderBy('breweries.zipcode', 'DESC')
            ->getQuery()
            ->execute();
    }

    public function findOpenBreweries()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $today = date("l");

        $query = $em->createQuery("SELECT b
        FROM AppBundle:Breweries b
        WHERE b.open = '$today'
        ");

        $result = $query->getResult();


        try {

            return $result;

        } catch (\Doctrine\ORM\NoResultException $e)
        {

            return null;

        }
    }

}
