<?php

namespace AppBundle\Repository;

/**
 * BreweriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use AppBundle\Entity\Breweries;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\ORM\Query;
use Symfony\Bridge\Doctrine\RegistryInterface;

class BreweriesRepository extends \Doctrine\ORM\EntityRepository
{

    public function findThreeNearestBreweries($input)
    {
        // automatically knows to select Breweries
        // the "p" is an alias you'll use in the rest of the query
        $qb = $this->createQueryBuilder('p')
            ->andWhere('p.zipcode > :zipcode')
//            ->setParameter('zipcode', $zipcode)
            ->orderBy('p.zipcode', 'ASC')
            ->getQuery();

        return $qb->execute();

        // to get just one result:
        // $product = $qb->setMaxResults(1)->getOneOrNullResult();
    }

    public function findOpenBrewery($input)
    {
        // automatically knows to select Breweries
        // the "p" is an alias you'll use in the rest of the query
        $qb = $this->createQueryBuilder('p')
            ->andWhere()
            ->orderBy('p.zipcode', 'ASC')
            ->getQuery();

        return $qb->execute();

        // to get just one result:
        // $product = $qb->setMaxResults(1)->getOneOrNullResult();
    }


}
